# Generated by Django 2.2.5 on 2019-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanpost',
            name='post_img',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='chanpost',
            name='post_ip',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='chanpostreply',
            name='reply_img',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='chanpostreply',
            name='reply_ip',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='chanpost',
            name='post_pw',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='chanpost',
            name='post_trip',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='chanpostreply',
            name='reply_pw',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='chanpostreply',
            name='reply_trip',
            field=models.CharField(default='', max_length=128),
        ),
    ]
