# Generated by Django 2.2.5 on 2019-09-15 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0006_auto_20190915_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chanpost',
            name='post_title',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='chanpostreply',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chanpostreply',
            name='reply_title',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
