# Generated by Django 2.2.5 on 2019-09-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0007_auto_20190915_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_container_board',
            new_name='container_board',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_pw',
            new_name='pw',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='post_trip',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_container_post',
            new_name='container_post',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_pw',
            new_name='pw',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='reply_trip',
            new_name='trip',
        ),
    ]
