# Generated by Django 2.2.5 on 2019-09-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0009_auto_20190915_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chanpost',
            old_name='pw',
            new_name='delete_password',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='chanpost',
            old_name='trip',
            new_name='tripcode',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='pw',
            new_name='delete_password',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='chanpostreply',
            old_name='trip',
            new_name='tripcode',
        ),
    ]
