# Generated by Django 2.2.5 on 2019-09-16 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0010_auto_20190915_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanpost',
            name='last_touch',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
