# Generated by Django 2.2.5 on 2019-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0011_chanpost_last_touch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanpost',
            name='delete_password',
        ),
        migrations.RemoveField(
            model_name='chanpostreply',
            name='delete_password',
        ),
    ]
