# Generated by Django 2.2.5 on 2019-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0012_auto_20190917_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanpost',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='chan_images/'),
        ),
        migrations.AlterField(
            model_name='chanpostreply',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='chan_images/'),
        ),
    ]
